//! Data models for the daily loop feature

use std::collections::HashMap;

use chrono::{NaiveDate, NaiveDateTime};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct ScheduledTask {
    pub id: String,
    pub task_id: String,
    pub title: String,
    pub start_time: String,
    pub duration_minutes: i32,
    #[serde(default)]
    pub estimate_source: Option<String>,
    #[serde(default)]
    pub eisenhower_quadrant: Option<String>,
}

/// A daily Agenda generated by the Assistant or created manually.
/// One per day per user.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DailyPlan {
    pub id: String,
    pub date: NaiveDate,
    /// IDs of the top 3 Outcome entities
    pub top_3_outcome_ids: Vec<String>,
    /// Ordered task IDs for the day
    pub task_order: Vec<String>,
    /// Human-readable titles for each task ID (persisted so titles survive app restarts)
    #[serde(default)]
    pub task_titles: HashMap<String, String>,
    /// Task IDs that have been checked off as completed
    #[serde(default)]
    pub completed_task_ids: Vec<String>,
    /// Local time used to generate the schedule
    #[serde(default)]
    pub generated_at: Option<String>,
    /// Concrete chronological schedule from agenda markdown
    #[serde(default)]
    pub scheduled_tasks: Vec<ScheduledTask>,
    /// When the plan was locked (end-of-day)
    pub locked_at: Option<NaiveDateTime>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

/// A measurable deliverable for the day (e.g., "Ship onboarding flow to staging").
/// Distinct from Task — Outcomes are what you achieve, Tasks are what you do.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Outcome {
    pub id: String,
    pub daily_plan_id: String,
    pub title: String,
    /// Task IDs that contribute to this outcome
    pub linked_task_ids: Vec<String>,
    pub created_at: NaiveDateTime,
    pub ai_generated: bool,
}

/// A record of a task being deferred. Each deferral event is a separate row.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Deferral {
    pub id: String,
    pub task_id: String,
    pub date: NaiveDate,
    pub reason: Option<String>,
    pub ai_interpretation: Option<String>,
    pub created_at: NaiveDateTime,
}

/// End-of-day check-in snapshot.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CheckIn {
    pub id: String,
    pub date: NaiveDate,
    pub completed_task_ids: Vec<String>,
    pub notes: Option<String>,
    pub ai_summary: Option<String>,
    pub created_at: NaiveDateTime,
}

/// Rolling AI-generated summary for context window management.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ContextSnapshot {
    pub id: String,
    pub date: NaiveDate,
    pub summary_text: String,
    pub token_count: i32,
    pub created_at: NaiveDateTime,
}

/// A single chat message within an Agenda session.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChatMessage {
    pub id: String,
    pub daily_plan_id: String,
    pub role: ChatRole,
    pub content: String,
    pub timestamp: NaiveDateTime,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ChatRole {
    User,
    Ai,
}

impl ChatRole {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::User => "user",
            Self::Ai => "ai",
        }
    }

    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "user" => Some(Self::User),
            "ai" => Some(Self::Ai),
            _ => None,
        }
    }
}

/// Aggregate statistics for a single day+domain.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DailyStats {
    pub date: NaiveDate,
    pub domain: String,
    pub planned_count: i32,
    pub completed_count: i32,
    pub deferred_count: i32,
    pub avg_task_minutes: f64,
}

/// Append-only snapshot of a plan's state at a point in time.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PlanRevision {
    pub id: String,
    pub daily_plan_id: String,
    pub revision_number: i32,
    /// Outcome IDs at this revision
    pub top_3: Vec<String>,
    /// Task order at this revision
    pub task_order: Vec<String>,
    /// What triggered this revision
    pub trigger: RevisionTrigger,
    pub timestamp: NaiveDateTime,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum RevisionTrigger {
    Initial,
    Chat,
    Manual,
}

impl RevisionTrigger {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Initial => "initial",
            Self::Chat => "chat",
            Self::Manual => "manual",
        }
    }

    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "initial" => Some(Self::Initial),
            "chat" => Some(Self::Chat),
            "manual" => Some(Self::Manual),
            _ => None,
        }
    }
}
